apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: selvi-ui
  name: selvi-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selvi-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selvi-ui
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 8080
        resources: {}
status: {}
